BMSApplication/BMSApplication/ViewModels/vInvoices.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BMSApplication.Models;

namespace BMSApplication.ViewModels
{
    public class vInvoices
    {
        public Invoice Invoice { get; set; }
        public IEnumerable<InvoiceItem> Items { get; set; }
    }
}

BMSApplication/BMSApplication/Controllers/vInvoiceController.cs
using BMSApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BMSApplication.Controllers
{
    public class vInvoiceController : Controller
    {
        private BMSApplicationContext db = new BMSApplicationContext();
        // GET: vInvoice
        public ActionResult Index()
        {
            return View();
        }

        // GET: vInvoice/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: vInvoice/Create
        public ActionResult Create()
        {
            ViewBag.SupplierId = new SelectList(db.Suppliers, "Id", "Name");
            ViewBag.VendorId = new SelectList(db.Vendors, "Id", "Brand");
            ViewBag.VarietyId = db.Varieties.Select(v => new SelectListItem { Value = v.Id.ToString(), Text = (v.Product.Name + " " + v.Size.Label + " " + v.Color.Label) }).ToList();
            return View();
        }

        // POST: vInvoice/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            ViewBag.SupplierId = new SelectList(db.Suppliers, "Id", "Name");
            ViewBag.VendorId = new SelectList(db.Vendors, "Id", "Brand");
            ViewBag.VarietyId = db.Varieties.Select(v => new SelectListItem { Value = v.Id.ToString(), Text = (v.Product.Name + " " + v.Size.Label + " " + v.Color.Label) }).ToList();

            try
            {
                // TODO: Add insert logic here
                ViewBag.Status = "Success";
                var inv = GetInvoice();
                if(inv != null)
                {
                    inv.Items = GetInvoiceItem();
                    db.Invoices.Add(inv);
                    db.SaveChanges();
                }
                else
                {
                    return View();
                }
                return RedirectToRoute(new { controller = "Invoices", action = "Index" });
            }
            catch
            {
                return View();
            }
        }

        private Invoice GetInvoice()
        {
            Invoice i = new Invoice();
            try
            {
                i.Number = Request.Form["Number"];
                i.Date = DateTime.Parse(Request.Form["Date"]);
                i.GSTCode = Request.Form["GSTCode"];
                i.GSTAmount = Request.Form["GSTAmount"];
                i.SupplierId = int.Parse(Request.Form["SupplierId"]);
                i.VendorId = int.Parse(Request.Form["VendorId"]);
                i.Type = Request.Form["Type"];
            }
            catch
            {
                return null;
            }
            return i;
        }

        private List<InvoiceItem> GetInvoiceItem()
        {
            string[] varieties = Request.Form["VarietyId[]"].Split(',');
            string[] costs = Request.Form["cost[]"].Split(',');
            string[] sells = Request.Form["sell[]"].Split(',');
            string[] qtys = Request.Form["qty[]"].Split(',');
            string[] total = Request.Form["total[]"].Split(',');
            var invitems = new List<InvoiceItem>();
            for (int i = 0; i<varieties.Length; i++)
            {
                invitems.Add(new InvoiceItem {
                    Price = double.Parse(costs[i]),
                    Quantity = int.Parse(qtys[i]),
                    Total = double.Parse(total[i]),
                    VarietyId = int.Parse(varieties[i])
                });
            }
            return invitems.Count > 0 ? invitems : null;
        }

        // GET: vInvoice/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: vInvoice/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: vInvoice/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: vInvoice/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

BMSApplication/BMSApplication/Views/vInvoice/Create.cshtml
@model BMSApplication.Models.Invoice

@{
    ViewBag.Title = "Create";
}
<link href="~/Content/dist/css/select2.min.css" rel="stylesheet"/>
<script src="~/Content/dist/select2/select2.full.min.js"></script>
<script src="~/Scripts/PageJs/vInvoice.js"></script>
@using (Html.BeginForm("Create", "vInvoice", FormMethod.Post, new { @class = "form-horizontal", @Id = "InvoiceForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="row">
        <div class="span5">
            <div class="widget widget-nopad">
                <div class="widget-header">
                    <i class="icon-list-alt"></i>
                    <h3> Invoice Details</h3>
                </div>
                <!-- /widget-header -->
                <div class="widget-content">
                    <div class="widget big-stats-container">
                        <div class="widget-content">
                            <fieldset style="padding-top:20px;">
                                <div class="control-group">
                                    @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label" })
                                    <div class="controls">
                                        @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "span2" } })
                                        @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="control-group">
                                    @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="controls">
                                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "span2" } })
                                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="control-group">
                                    @Html.LabelFor(model => model.GSTCode, htmlAttributes: new { @class = "control-label" })
                                    <div class="controls">
                                        @Html.EditorFor(model => model.GSTCode, new { htmlAttributes = new { @class = "span2" } })
                                        @Html.ValidationMessageFor(model => model.GSTCode, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="control-group">
                                    @Html.LabelFor(model => model.GSTAmount, htmlAttributes: new { @class = "control-label" })
                                    <div class="controls">
                                        @Html.EditorFor(model => model.GSTAmount, new { htmlAttributes = new { @class = "span2" } })
                                        @Html.ValidationMessageFor(model => model.GSTAmount, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label for="SupplierId" class="control-label">Supplier</label>
                                    <div class="controls">
                                        @Html.DropDownList("SupplierId", null, "Select Supplier", htmlAttributes: new { @class = "span2", require = string.Empty })
                                        @Html.ValidationMessageFor(model => model.SupplierId, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="control-group">
                                    <label for="VendorId" class="control-label">Vendor</label>
                                    <div class="controls">
                                        @Html.DropDownList("VendorId", null, "Select Vendor", htmlAttributes: new { @class = "span2" })
                                        @Html.ValidationMessageFor(model => model.VendorId, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="control-group">
                                    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="controls">
                                        @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "span2" } })
                                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="control-group">
                                    <div class="controls">
                                        <input type="submit" class="btn btn-success" />
                                        <input type="reset" class="btn btn-warning" />
                                        @*@Html.RouteLink("Cancel", "Invoices", null, new { @class = "btn btn-danger", @style = "width:60px" })*@
                                    </div>
                                </div>
                            </fieldset>
                        </div>
                        <!-- /widget-content -->

                    </div>
                </div>
            </div>
        </div>

        <div class="span7">
            <div class="widget widget-nopad">
                <div class="widget-header">
                    <i class="icon-list-alt"></i>
                    <h3> Invoice Items</h3>
                </div>
                <!-- /widget-header -->
                <div class="widget-content">
                    <div class="widget big-stats-container">
                        <div class="widget-content">
                            <table class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th class="span1">Cost</th>
                                        <th class="span1">Qty</th>
                                        <th class="span1">Total</th>
                                        <th class="span1">Action</th>
                                    </tr>
                                </thead>
                                <tbody id="invoiceitem">
                                    <tr>
                                        <td>@Html.DropDownList("VarietyId", null, "Select Product", htmlAttributes: new { @Id = "varietyselect", @Class = "", @Name = "VarietyId[]" })</td>
                                        <td><input class="span1 invoiceitemform" type="text" id="cost" name="cost[]" /></td>
                                        <td><input class="span1 invoiceitemform" type="text" id="qty" name="qty[]" value="1" /></td>
                                        <td><input class="span1" type="text" id="total" name="total[]" /></td>
                                        <td><input type="button" id="removeitem" value="X" class="btn btn-danger span1" /></td>
                                    </tr>
                                </tbody>
                                <tr>
                                    <td colspan="3">Grand Total</td>
                                    <td><input class="span1" type="text" id="grandtotal" name="grandtotal" disabled /></td>
                                    <td></td>
                                </tr>
                            </table>
                            <div style="padding-left:3%">
                                <input type="button" id="btnAddItem" value="Add Item" class="btn btn-info" style="width:100px" />
                            </div>
                        </div>
                        <!-- /widget-content -->
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<div style="display:none;">
    <table>
        <tr id="original">
            <td>@Html.DropDownList("VarietyId", null, "Select Product", htmlAttributes: new { @Id = "varietyselect", @Class = "", @Name = "VarietyId[]" })</td>
            <td><input class="span1 invoiceitemform" type="text" id="cost" name="cost[]" /></td>
            <td><input class="span1 invoiceitemform" type="text" id="qty" name="qty[]" value="1" /></td>
            <td><input class="span1" type="text" id="total" name="total[]" /></td>
            <td><input type="button" id="removeitem" value="X" class="btn btn-danger span1" /></td>
        </tr>
    </table>
</div>