BMSApplication/BMSApplication/ViewModels/CounterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BMSApplication.Models;

namespace BMSApplication.ViewModels
{
    public class CounterViewModel
    {
        public Transaction Transaction { get; set; }
    }
}

BMSApplication/BMSApplication/Controllers/CounterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BMSApplication.Models;
using BMSApplication.ViewModels;
using System.Net;

namespace BMSApplication.Controllers
{
    public class CounterController : Controller
    {
        private BMSApplicationContext db = new BMSApplicationContext();
        // GET: Counter
        public ActionResult Index()
        {
            
            ViewBag.MemberId = new SelectList(db.Members, "Id", "Name");
            ViewBag.ChannelId = new SelectList(db.Channels, "Id", "Label");
            object[] payment = new object[2];
            payment[0] = "Cash";
            payment[1] = "Credit Card";
            ViewBag.PaymentMethod = new SelectList(payment);
            var varieties = db.Varieties.Include(v => v.Color).Include(v => v.Product).Include(v => v.Size);
           
           return View(varieties.ToList());
            
        }
        //[Route("customer/detail/{id}")]
        public ActionResult Details(int? id)
        {
            /*ViewBag.Tendered = 3;
            return View();*/
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Receipt receipt = db.Receipts.Find(id);
            if (receipt == null)
            {
                return HttpNotFound();
            }
            
            ViewBag.Transaction = db.Transactions.Where(t => t.ReceiptId == id);
            //Console.WriteLine(ViewBag.Transaction);
            return View(receipt);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int[] quantity, double[] cost, int[] id, double[] sell, double tendered, double totalCost, int MemberId, string PaymentMethod, double change, int ChannelId, string credit_invoice)
        {
            //var variety = db.Varieties.FirstOrDefault(u => u.Id == 1);
            Receipt receipt = new Receipt();
            receipt.MemberId = MemberId;
            receipt.Method = PaymentMethod;
            receipt.Tendered = tendered;
            receipt.Total = totalCost;
            receipt.Change = change;
            receipt.CreditCardInvoice = credit_invoice;
            receipt.Date = DateTime.Now;
            db.Receipts.Add(receipt);
            db.SaveChanges();
            int receiptId = receipt.Id;

            int count = 0;
            foreach(var i in id)
            {
                var variety = db.Varieties.FirstOrDefault(u => u.Id == i);
                variety.Quantity = variety.Quantity - quantity[count];
                db.Entry(variety).State = EntityState.Modified;
                db.SaveChanges();
                Transaction transaction = new Transaction();
                transaction.VarietyId = i;
                transaction.Date = DateTime.Now;
                transaction.ReceiptId = receiptId;
                transaction.UserId = 1;
                transaction.Sell = sell[count];
                transaction.ChannelId = ChannelId;
                transaction.Quantity = quantity[count];
                db.Transactions.Add(transaction);
                db.SaveChanges();
                //variety.Quantity -
                //Console.WriteLine(i);
                count++;
            }



            //return Content(receiptId.ToString());
            return RedirectToAction("Details/" + receiptId);
        }
        

    }
}

BMSApplication/BMSApplication/Views/Counter/Details.cshtml
@model BMSApplication.Models.Receipt

@{
    ViewBag.Title = "Details";
}

<div class="main">
    <div class="main-inner">
        <div class="container">
            <div class="row">
                <div class="span6">
                    <div class="widget widget-nopad">
                        <div class="widget-header">
                            <i class="icon-inbox"></i>
                            <h3>Counter Page</h3>
                        </div> <!-- /widget-header -->
                        <div class="widget-content">
                            
                            <h1>Zhanna Boutique</h1>
                            <p>Date : @Html.DisplayFor(model => model.Date)</p>

                            <p> Method: @Html.DisplayFor(model => model.Method)</p>

                            @{
                                var listUser = (System.Data.Entity.Infrastructure.DbQuery<BMSApplication.Models.Transaction>)ViewBag.Transaction;
                            }
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Quantity</th>
                                        <th>Price</th>
                                        <th>Total Price</th>
                                    </tr>
                                </thead>
                                @foreach (var tran in listUser)
                                {
                                    <tr>
                                        <td>@tran.Variety.Product.Name - @tran.Variety.Color.Label - @tran.Variety.Size.Label</td>
                                        <td>X @tran.Quantity</td>
                                        <td>@tran.Sell</td>
                                        <td>@((tran.Sell * tran.Quantity))</td>
                                    </tr>

                                }
                                <tr>
                                    <td><strong>Total : </strong></td>
                                    <td></td>
                                    <td></td>
                                    <td>@Html.DisplayFor(model => model.Total)</td>
                                    
                                </tr>
                                <tr>
                                    <td>
                                        <strong>Tendered : </strong>  @Html.DisplayFor(model => model.Tendered)
                                    </td>
                                    <td></td>
                                    <td></td>
                                    <td>
                                        <strong>Change :</strong> @Html.DisplayFor(model => model.Change)
                                    </td>
                                </tr>

                            </table>

                            <center>
                                <p>
                                    @Html.ActionLink("Print", "", null, new { @class = "btn btn-default" }) | @Html.ActionLink("Next Customer", "Index", null, new { @class = "btn btn-success" })
                                </p>
                            </center>
                        </div>
                        </div>
                   </div>
               </div>
           </div>
       </div>
   </div>


                       

BMSApplication/BMSApplication/Views/Counter/Index.cshtml
@model IEnumerable<BMSApplication.Models.Variety>
@{
    ViewBag.Title = "Index";
}


<div class="main">
    <div class="main-inner">
        <div class="container">
            <div class="row">
                <div class="span6">
                    <div class="widget widget-nopad">
                        <div class="widget-header">
                            <i class="icon-inbox"></i>
                            <h3>Counter Page</h3>
                        </div> <!-- /widget-header -->

                        <div class="widget-content">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Product</th>
                                        <th>Quantity</th>
                                        <th>Sell Price</th>
                                    </tr>
                                </thead>
                                @{
                                    int count = 0;
                                }
                                @foreach (var item in Model)
                                {
                                    count++;
                                    var classNama = "data" + count;
                                    <tr>
                                        <td>
                                            <button id=@classNama class="actionBtn btn btn-default">@item.Product.Name - @item.Color.Label - @item.Size.Label</button>
                                        </td>
                                        <td>
                                            @item.Quantity
                                        </td>
                                        <td>
                                            @item.Product.Sell
                                        </td>
                                    </tr>
                                    
                                    <input id=@classNama-cost type="hidden" value=@item.Product.Sell />
                                    <input id=@classNama-quantity type="hidden" value=@item.Quantity />
                                    <input id=@classNama-id type="hidden" value="@item.Id" />
                                    <input id=@classNama-sell type="hidden" value="@item.Product.Sell" />
                                    
                                }
                            </table>
                        </div>
                    </div>
                </div>
                <div class="span6">
                    <div class="widget">
                        <div class="widget-header">
                            <i class="icon-bookmark"></i>
                            <h3>Cart</h3>
                        </div>
                        <div class="widget-content">
                            <div id="myform">

                                @using (Html.BeginForm("Edit", "Counter", FormMethod.Post, new { @class = "form-horizontal" }))
                                {
                                    @Html.AntiForgeryToken()
                                    <fieldset>
                                            <table class='table table-striped'>
                                                <thead><tr><th>Product Name</th><th>Quantity</th><th>Price</th><th>Sell</th><th></th></tr></thead>
                                                <tbody id="test">

                                                </tbody>
                                            </table>
                                            <table class="table table-striped">
                                                <thead>
                                                    <tr>
                                                        <th>Tendered</th>
                                                        <th>Total</th>
                                                        <th>Change</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr>
                                                        <td><input type="text" id="tendered" class="span1" name="tendered" value="0" /></td>
                                                        <td><input type="text" id="totalCost" class="span1" name="totalCost" value="0" /></td>
                                                        <td><input type="text" id="change" class="span1" name="change" /></td>
                                                        <input id="previous-price" type="hidden" value="0" />
                                                    </tr>
                                                </tbody>
                                            </table>
                                        <table class="table">
                                                <tr>
                                                    <th>Members</th>
                                                    <th>Channel</th>
                                                </tr>
                                                <tr>
                                                    <td>@Html.DropDownList("MemberId", null, new { @class = ""})</td>
                                                    <td>@Html.DropDownList("ChannelId", null, new { @class = "" })</td>
                                                </tr>
                                                <tr>
                                                    <th>Method</th>
                                                    <th>Credit Card Invoice</th>
                                                </tr>
                                                 <tr>
                                                     <td>@Html.DropDownList("PaymentMethod", null, new { @class = "" })</td>
                                                     <!-- <td><input type="text" id="method" name="method" class="span" /></td> -->
                                                     <td><input type="text" id="credit_invoice" name="credit_invoice" class="span" /></td>
                                                 </tr>
                                                <tr>
                                                    <td colspan="3" style="text-align:right"><button id="btnSubmit" class="btn btn-warning">Checkout</button></td>
                                                </tr>
          
                                        </table>
                                            
                                            </fieldset>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
</div>
        </div>
</div>